services:
  planadatabase:
    container_name: plana_database
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: plana
    ports:
      - "5436:5432"
    volumes:
      - ./planadata:/var/lib/postgres

  planaserver:
    build: ./
    container_name: plana_server
    depends_on:
      - planadatabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["sh", "-c", "npx prisma db push && npm start"]

volumes:
  planadata:
